name: pop_pop_win
publish_to: none

environment:
  sdk: '>=2.11.99 <3.0.0'

dependencies:
  js: ^0.6.1
  stagexl: ^2.0.0

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.3.0
  preload: ^2.0.0
  test: ^1.0.0
