name: poppopwin
author: Kevin Moore <kevmoo@google.com>
homepage: https://github.com/dart-lang/pop-pop-win
description: '"Pop, Pop, Win!" is an implementation of Minesweeper in Dart.'
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  bot: '>=0.25.3'
  bot_web: '>=0.21.0'
  browser: '>=0.9.0 <0.10.0'
  chrome_gen: '>=0.3.4'
dev_dependencies:
  hop: '>=0.28.1+2'
