name: pop_pop_win
author: Dart Team <misc@dartlang.org>
description: '"Pop, Pop, Win!" is an implementation of Minesweeper in Dart.'
homepage: https://github.com/dart-lang/sample-pop_pop_win
environment:
  sdk: '>=2.0.0-dev.48.0 <3.0.0'
dependencies:
  js: ^0.6.1
  stagexl: ^1.4.0-dev
dev_dependencies:
  test: ^1.0.0
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
