name: poppopwin
author: Kevin Moore <kevin@thinkpixellab.com>
description: '"Pop, Pop, Win!" is an implementation of Minesweeper in Dart.'
homepage: https://github.com/dart-lang/pop-pop-win
environment:
  sdk: '>=0.6.3'
dependencies:
  bot: '>=0.22.1'
  bot_web: '>=0.20.1'
  js: '>=0.0.23'
dev_dependencies:
  hop: '>=0.23.0'
